module.exports = [
  {
    id: 1,
    title: "Banana",
    description: "Dog with a banana toy",
    width: 350,
    height: 500,
    path: "banana-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 2,
    title: "bear",
    description: "Dog in a bear costume",
    width: 350,
    height: 500,
    path: "bear-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 3,
    title: "Bow",
    description: "Dapper dog with a bowtie",
    width: 350,
    height: 500,
    path: "bow-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 4,
    title: "Cow",
    description: "Dog with his favorite toy cow",
    width: 350,
    height: 500,
    path: "congee-cow",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 5,
    title: "Happy",
    description: "A really happy dog",
    width: 350,
    height: 500,
    path: "happy-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 6,
    title: "scarf",
    description: "A fashionable dog with a scarf",
    width: 350,
    height: 500,
    path: "scarf-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 7,
    title: "Shapespeare",
    description: "Dog with a collar thing that looks like Shakespeare",
    width: 350,
    height: 500,
    path: "shakesp-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 8,
    title: "Shoes",
    description: "Dog wearing shoes",
    width: 350,
    height: 500,
    path: "shoes-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
  {
    id: 9,
    title: "Sleeping",
    description: "Dog taking a bit of a snooze",
    width: 350,
    height: 500,
    path: "sleeping-gallery",
    link: "https://dogtime.com/dog-breeds/maltese-shih-tzu",
    credit: "Erica",
    creditURL: "https://www.instagram.com/etrinhh/?hl=en",
  },
];
